# Generated by Django 2.2 on 2020-07-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei_number', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=150)),
                ('mobile_company', models.CharField(max_length=100)),
                ('mobile_model', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
            ],
        ),
    ]
